/*  eslint-disable no-new */
import 'babel-polyfill';

import Vue from 'vue';
import VueProgressiveImage from 'vue-progressive-image';

import BootstrapCMSTables from 'components/tables/BootstrapCMSTables';
import ToggleBlock from 'components/toggle/ToggleBlock.vue';
import ToggleGroup from 'components/toggle/ToggleGroup.vue';
import ToggleBlockMobile from 'components/toggle/ToggleBlockMobile.vue';
import Accordion from 'components/accordion/Accordion.vue';
import AlumniProfiles from 'components/profiles/alumni-profiles/AlumniProfiles.vue';
import AccordionGroup from 'components/accordion/AccordionGroup.vue';
import CheckList from 'components/check-list';
import MegaMenu from 'components/megamenu';
import MegaMenuTitle from 'components/megamenu/MegaMenuTitle.vue';
import ModalDialog from 'components/modal';
import PageNav from 'components/nav';
import PageSearch from 'components/search';
import PageSearchForm from 'components/search/PageSearchForm.vue';
import { PageFooter, PageFooterAlt } from 'components/footer';
import Tabs from 'components/tabs/Tabs.vue';
import Tab from 'components/tabs/Tab.vue';
import InPageNavigation from 'components/navigation/InPageNavigation.vue';
import FocusWrapper from 'components/focus-wrapper/FocusWrapper.vue';
import SvgIcon from 'components/icons/SvgIcon.vue';
import ListingWrap from 'components/listing/ListingWrap.vue';
import ListItem from 'components/listing/ListItem.vue';
import ArticleWrap from 'components/article-wrap/ArticleWrap.vue';
import BlockQuotation from 'components/block-quotation/BlockQuotation.vue';
import ButtonIcon from 'components/buttons/ButtonIcon.vue';
import GenericCard from 'components/cards/GenericCard.vue';
import ContactList from 'components/contact-list/ContactList.vue';
import ContentBlock from 'components/content-block/ContentBlock.vue';
import Dropdown from 'components/dropdown/Dropdown.vue';
import VideoEmbed from 'components/embed/VideoEmbed.vue';
import VideoPlayer from 'components/embed/VideoPlayer.vue';
import VideoFullWidth from 'components/embed/VideoFullWidth.vue';
import SoundcloudEmbed from 'components/embed/SoundcloudEmbed.vue';
import FigureWrap from 'components/figure/FigureWrap.vue';
import Notice from 'components/notice/Notice.vue';
import PageBreadcrumbs from 'components/breadcrumbs/PageBreadcrumbs.vue';
import PageHeader from 'components/header/PageHeader.vue';
import PageHeaderMin from 'components/header/PageHeaderMin.vue';
import PageHeaderAlt from 'components/header/PageHeaderAlt.vue';
import PageHeaderStudy from 'components/header/PageHeaderStudy.vue';
import PageHeaderHome from 'components/header/PageHeaderHome.vue';
import Pathfinder from 'components/pathfinder/Pathfinder.vue';
import SectionDivider from 'components/section/SectionDivider.vue';
import SectionTwoCol from 'components/section/SectionTwoCol.vue';
import SectionWrap from 'components/section/SectionWrap.vue';
import SectionAlt from 'components/section/SectionAlt.vue';
import SectionImage from 'components/section/SectionImage.vue';
import SplitSection from 'components/section/SplitSection.vue';
import SplitSectionQuote from 'components/section/SplitSectionQuote.vue';
import SidePanel from 'components/side-panel/SidePanel.vue';
import SidePanelNavItem from 'components/side-panel/SidePanelNavItem.vue';
import SocialList from 'components/social-list/SocialList.vue';
import StatsGroup from 'components/stats/StatsGroup.vue';
import StatsItem from 'components/stats/StatsItem.vue';
import SublinkMenu from 'components/sublink-menu/SublinkMenu.vue';
import SublinkMenuItem from 'components/sublink-menu/SublinkMenuItem.vue';
import Welcome from 'components/welcome/Welcome.vue';
import CardImage from 'components/cards/CardImage.vue';
import CardLink from 'components/cards/CardLink.vue';
import CardStaffList from 'components/cards/CardStaffList.vue';
import CardStat from 'components/cards/CardStat.vue';
import AccordionProfile from 'components/profiles/accordion-profile/AccordionProfile.vue';
import CardEvents from 'components/cards/CardEvents.vue';
import CardFeaturesPanel from 'components/cards/CardFeaturesPanel.vue';
import MediaGallery from 'components/media-gallery/MediaGallery.vue';
import CardNews from 'components/cards/CardNews.vue';
import Heading1 from 'components/typography/headings/Heading1.vue';
import Heading2 from 'components/typography/headings/Heading2.vue';
import Heading3 from 'components/typography/headings/Heading3.vue';
import Heading4 from 'components/typography/headings/Heading4.vue';
import Heading5 from 'components/typography/headings/Heading5.vue';
import Heading6 from 'components/typography/headings/Heading6.vue';
import SocialMediaBar from 'components/social-media-bar/SocialMediaBar.vue';
import Testimonials from 'components/testimonials/Testimonials.vue';
import TestimonialsAlt from 'components/testimonials/TestimonialsAlt.vue';
import InfoPanel from 'components/info-panel/InfoPanel.vue';
import CompactedTable from 'components/tables/CompactedTable.vue';
import ResponsiveTable from 'components/tables/ResponsiveTable.vue';
import PageHeaderCampaign from 'components/campaign/PageHeaderCampaign.vue';
import Carousel from 'components/carousel/Carousel.vue';
import Logo from 'components/logo/Logo.vue';
import CardsFilter from 'components/filter/cards/CardsFilter.vue';
import AccordionFilter from 'components/filter/accordion/AccordionFilter.vue';
import FilterDropdown from 'components/filters/components/filter-dropdown/FilterDropdown.vue';
import FilterBox from 'components/filters/components/filter-box/FilterBox.vue';
import FilteredResults from 'components/filters/components/filtered-results/FilteredResults.vue';
import FilterWidget from 'components/filters/components/filter-widget/FilterWidget.vue';
import Tags from 'components/tags/Tags.vue';
import CardNewsTag from 'components/cards/CardNewsTag.vue';
import PageHeaderEvent from 'components/header/PageHeaderEvent.vue';
import Sidebar from 'components/sidebar/Sidebar.vue';
import SocialListGeneric from 'components/social-list/SocialListGeneric.vue';
import LogoListing from 'components/listing/LogoListing.vue';
import SplitSectionHeader from 'components/header/SplitSectionHeader.vue';
import ScreenReaderJumpTo from 'components/screen-reader-jump-to/ScreenReaderJumpTo.vue';
import StyledSelect from 'components/forms/StyledSelect.vue';
import InlineSearch from 'components/forms/InlineSearch.vue';
import AppCheckbox from 'components/app-checkbox/AppCheckbox.vue';
import Spinner from 'components/loader/Spinner.vue';
import Loader from 'components/loader/Loader.vue';
import LoadingOverlay from 'components/loader/LoadingOverlay.vue';
import ErrorBox from 'components/error-box/ErrorBox.vue';
import CardCourse from 'components/cards/CardCourse.vue';
import CardCourseList from 'components/cards/CardCourseList.vue';
import ButtonTwoIcons from 'components/buttons/ButtonTwoIcons.vue';
import ButtonCard from 'components/buttons/ButtonCard.vue';
import CardCampaign from 'components/cards/CardCampaign.vue';
import PageCampaignCards from 'components/campaign/PageCampaignCards.vue';
import FigureRounded from 'components/figure/FigureRounded.vue';
import CardRoundedFigure from 'components/cards/CardRoundedFigure.vue';
import TodoList from 'components/todo-list/TodoList.vue';
import CampaignBanner from 'components/campaign/CampaignBanner.vue';
import CampaignBannerAlt from 'components/campaign/CampaignBannerAlt.vue';
import CardImageLink from 'components/cards/CardImageLink.vue';
import CardsFilterCategory from 'components/filter/cards-category/CardsFilterCategory.vue';
import CoursesFilter from 'components/filter/courses/CoursesFilter.vue';
import PathfinderToday from 'components/today/PathfinderToday/PathfinderToday.vue';
import QuickLinksAlt from 'components/quick-links-menu/QuickLinksAlt.vue';
import MegaMenuAlt from 'components/megamenu/MegaMenuAlt.vue';
import CardFlat from 'components/cards/CardFlat.vue';
import CardFlatList from 'components/cards/CardFlatList.vue';
import CardArticle from 'components/cards/CardArticle.vue';
import CardArticleLarge from 'components/cards/CardArticleLarge.vue';
import CardArticleList from 'components/cards/CardArticleList.vue';

import 'components';

// Load shared SVG assets
require.context('components/shared', false, /\.svg$/);

// Register Vue plugins, directives and components
Vue.use(VueProgressiveImage);
Vue.component('toggle-block', ToggleBlock);
Vue.component('toggle-group', ToggleGroup);
Vue.component('toggle-block-mobile', ToggleBlockMobile);
Vue.component('accordion', Accordion);
Vue.component('accordion-group', AccordionGroup);
Vue.component('check-list', CheckList);
Vue.component('mega-menu', MegaMenu);
Vue.component('mega-menu-title', MegaMenuTitle);
Vue.component('modal-dialog', ModalDialog);
Vue.component('page-footer', PageFooter);
Vue.component('page-footer-alt', PageFooterAlt);
Vue.component('page-nav', PageNav);
Vue.component('page-search', PageSearch);
Vue.component('page-search-form', PageSearchForm);
Vue.component('tabs', Tabs);
Vue.component('tab', Tab);
Vue.component('in-page-navigation', InPageNavigation);
Vue.component('focus-wrapper', FocusWrapper);
Vue.component('svg-icon', SvgIcon);
Vue.component('listing-wrap', ListingWrap);
Vue.component('list-item', ListItem);
Vue.component('article-wrap', ArticleWrap);
Vue.component('block-quotation', BlockQuotation);
Vue.component('button-icon', ButtonIcon);
Vue.component('generic-card', GenericCard);
Vue.component('card-staff-list', CardStaffList);
Vue.component('contact-list', ContactList);
Vue.component('content-block', ContentBlock);
Vue.component('dropdown', Dropdown);
Vue.component('video-embed', VideoEmbed);
Vue.component('sound-cloud-embed', SoundcloudEmbed);
Vue.component('figure-wrap', FigureWrap);
Vue.component('notice', Notice);
Vue.component('page-breadcrumbs', PageBreadcrumbs);
Vue.component('page-header', PageHeader);
Vue.component('page-header-min', PageHeaderMin);
Vue.component('page-header-event', PageHeaderEvent);
Vue.component('page-header-alt', PageHeaderAlt);
Vue.component('pathfinder', Pathfinder);
Vue.component('section-divider', SectionDivider);
Vue.component('section-two-col', SectionTwoCol);
Vue.component('section-wrap', SectionWrap);
Vue.component('section-alt', SectionAlt);
Vue.component('section-image', SectionImage);
Vue.component('split-section', SplitSection);
Vue.component('slit-section-quote', SplitSectionQuote);
Vue.component('side-panel', SidePanel);
Vue.component('side-panel-nav-item', SidePanelNavItem);
Vue.component('social-list', SocialList);
Vue.component('stats-group', StatsGroup);
Vue.component('stats-item', StatsItem);
Vue.component('sublink-menu', SublinkMenu);
Vue.component('sublink-menu-item', SublinkMenuItem);
Vue.component('welcome', Welcome);
Vue.component('card-image', CardImage);
Vue.component('card-link', CardLink);
Vue.component('card-stat', CardStat);
Vue.component('card-accordion-profile', AccordionProfile);
Vue.component('card-events', CardEvents);
Vue.component('card-features-panel', CardFeaturesPanel);
Vue.component('media-gallery', MediaGallery);
Vue.component('card-news', CardNews);
Vue.component('heading1', Heading1);
Vue.component('heading2', Heading2);
Vue.component('heading3', Heading3);
Vue.component('heading4', Heading4);
Vue.component('heading5', Heading5);
Vue.component('heading6', Heading6);
Vue.component('social-media-bar', SocialMediaBar);
Vue.component('alumni-profiles', AlumniProfiles);
Vue.component('testimonials', Testimonials);
Vue.component('testimonials-alt', TestimonialsAlt);
Vue.component('info-panel', InfoPanel);
Vue.component('compacted-table', CompactedTable);
Vue.component('responsive-table', ResponsiveTable);
Vue.component('page-header-campaign', PageHeaderCampaign);
Vue.component('page-header-study', PageHeaderStudy);
Vue.component('page-header-home', PageHeaderHome);
Vue.component('carousel', Carousel);
Vue.component('logo', Logo);
Vue.component('cards-filter', CardsFilter);
Vue.component('accordion-filter', AccordionFilter);
Vue.component('filter-dropdown', FilterDropdown);
Vue.component('filter-box', FilterBox);
Vue.component('filtered-results', FilteredResults);
Vue.component('filter-widget', FilterWidget);
Vue.component('tags', Tags);
Vue.component('card-news-tag', CardNewsTag);
Vue.component('sidebar', Sidebar);
Vue.component('social-list-generic', SocialListGeneric);
Vue.component('logo-listing', LogoListing);
Vue.component('split-section-header', SplitSectionHeader);
Vue.component('screen-reader-jump-to', ScreenReaderJumpTo);
Vue.component('styled-select', StyledSelect);
Vue.component('inline-search', InlineSearch);
Vue.component('app-checkbox', AppCheckbox);
Vue.component('spinner', Spinner);
Vue.component('loader', Loader);
Vue.component('loading-overlay', LoadingOverlay);
Vue.component('error-box', ErrorBox);
Vue.component('card-course', CardCourse);
Vue.component('card-course-list', CardCourseList);
Vue.component('button-two-icons', ButtonTwoIcons);
Vue.component('button-card', ButtonCard);
Vue.component('card-campaign', CardCampaign);
Vue.component('page-campaign-cards', PageCampaignCards);
Vue.component('figure-rounded', FigureRounded);
Vue.component('card-rounded-figure', CardRoundedFigure);
Vue.component('todo-list', TodoList);
Vue.component('campaign-banner', CampaignBanner);
Vue.component('campaign-banner-alt', CampaignBannerAlt);
Vue.component('card-image-link', CardImageLink);
Vue.component('cards-filter-category', CardsFilterCategory);
Vue.component('courses-filter', CoursesFilter);
Vue.component('pathfinder-today', PathfinderToday);
Vue.component('quick-links-alt', QuickLinksAlt);
Vue.component('video-player', VideoPlayer);
Vue.component('video-full-width', VideoFullWidth);
Vue.component('mega-menu-alt', MegaMenuAlt);
Vue.component('card-flat', CardFlat);
Vue.component('card-flat-list', CardFlatList);
Vue.component('card-article', CardArticle);
Vue.component('card-article-large', CardArticleLarge);
Vue.component('card-article-list', CardArticleList);

// Create Vue instance
new Vue({
  el: '#ui',
  beforeCreate() {
    BootstrapCMSTables(); // Add responsive classes to CMS tables.
  },
});
